export const invoicesItems = [
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High  Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
  {
    name: " Aquatak High Pressure Wash.",
    price: "$5,200",
    discription: "	Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    discount: "60",
    date: "12 Jan 2021",
  },
];
